x-process-variables: &process-variables
  PUID : 1000
  PGID : 1000
  # PUSER_PRIV_DROP : 'false'

services:
  redis:
    image: oci.guero.org/redis:latest
    container_name: searxng-redis
    restart: unless-stopped
    networks:
      - proxy
    environment:
      << : *process-variables
    command:
      - sh
      - -c
      - redis-server
    volumes:
      - redis-data:/data

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_HOSTNAME=search.example.org
      - SEARXNG_BASE_URL=https://search.example.org/
      - GRANIAN_HOST=0.0.0.0
      - SEARXNG_BIND_ADDRESS=0.0.0.0
      - SEARXNG_VALKEY_URL=redis://redis:6379/0
    labels:
      - "traefik.enable=false"
      # - "traefik.http.routers.searxng.rule=Host(`search.example.org`)"
      # - "traefik.http.routers.searxng.entrypoints=websecure"
      # - "traefik.http.routers.searxng.tls.certresolver=myresolver"

networks:
  proxy:
    external: true
    name: traefik-proxy

volumes:
  redis-data:
  searxng-data:
