name: audacity-build-push-ghcr

on:
  push:
    branches:
      - 'master'
    paths:
      - 'audacity/**'
  workflow_dispatch:
  repository_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/audacity
  IMAGE_TAG: latest
  REPO_CONTEXT: ./audacity
  REPO_CONTAINERFILE: ./audacity/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
    steps:
      -
        name: Cancel previous run in progress
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Log in to registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          context: ${{ env.REPO_CONTEXT }}
          containerfiles: |
            ${{ env.REPO_CONTAINERFILE }}
      -
        name: Push
        id: push-base-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
