---
name: audacity-build-push-ghcr

on:
  push:
    branches:
      - 'master'
    paths:
      - 'audacity/**'
      - '.github/workflows/audacity-build-push-ghcr.yml'
  pull_request:
    paths:
      - 'audacity/**'
      - '.github/workflows/audacity-build-push-ghcr.yml'
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'

jobs:
  build-image:
    name: Call Docker Build
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: ./audacity
      file: ./audacity/Dockerfile
      cancel-previous-runs: true
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/audacity
      tag-rules: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value=stable-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
        type=ref,event=pr
        type=ref,event=branch
        type=raw,value=gha-${{ github.run_id }}
      platforms: linux/amd64
